name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install pyinstaller PyQt6 PyQt6-WebEngine
    - name: Build with PyInstaller
      run: |
        pyinstaller --clean --noconsole --onefile --add-data "home.html;." omnikeen.py
    - uses: actions/upload-artifact@v4
      with:
        name: omnikeen-exe
        path: dist/omnikeen.exe
